version: '3.3'

services:

  currency-postgres:
    container_name: currency-postgres
    hostname: currency-postgres
    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    image: postgres:15
    networks:
      - home

  currency-app:
    container_name: currency-app
    hostname: currency-app
    build:
      context: .
      dockerfile: ./src/currency_app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/currency_app/logs/:/currency/src/currency_app/logs/
    depends_on:
      - currency-postgres
    networks:
      - home


#  alf-bot-nginx:
#    container_name: alf-bot-nginx
#    hostname: alf-bot-nginx
#    image: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - alf-bot-fastapi
#      - alf-bot-aiogram
#    networks:
#      - home



networks:
  home: {}
