"""initial

Revision ID: 6fbdee36a207
Revises: 
Create Date: 2023-10-27 23:35:51.682850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbdee36a207'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updatetime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=True),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_updatetime_id'), 'updatetime', ['id'], unique=False)
    op.create_table('currency',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('updatetime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updatetime_id'], ['updatetime.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=True)
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_updatetime_id'), table_name='updatetime')
    op.drop_table('updatetime')
    # ### end Alembic commands ###
